In [141]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

In [142]:
df = pd.read_csv("../data/raw/credit.csv")
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,90000,2,2,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
2,50000,2,2,1,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
3,50000,1,2,1,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
4,50000,1,1,2,37,0,0,0,0,0,...,19394.0,19619.0,20024.0,2500.0,1815.0,657.0,1000.0,1000.0,800.0,0

In [143]:
df[df.duplicated(keep=False)].sort_values(by=list(df.columns))

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
9938,20000,1,2,2,24,2,2,4,4,4,...,1650.0,1650.0,1650.0,0.0,0.0,0.0,0.0,0.0,0.0,1
11413,20000,1,2,2,24,2,2,4,4,4,...,1650.0,1650.0,1650.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1422,50000,1,2,2,26,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
8197,50000,1,2,2,26,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5761,50000,2,1,2,23,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13584,50000,2,1,2,23,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5925,80000,2,2,1,31,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
15270,80000,2,2,1,31,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
17391,80000,2,2,2,25,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
22184,80000,2,2,2,25,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5464,80000,2,3,1,42,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
23156,80000,2,3,1,42,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
18142,90000,2,1,2,31,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
20969,90000,2,1,2,31,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1293,150000,2,1,1,31,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3675,150000,2,1,1,31,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1588,150000,2,1,1,38,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1601,150000,2,1,1,38,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3896,150000,2,1,2,28,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
22319,150000,2,1,2,28,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
7531,160000,1,2,2,28,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12336,160000,1,2,2,28,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
989,160000,2,3,2,26,-1,-1,-1,-1,-1,...,390.0,390.0,390.0,390.0,390.0,390.0,390.0,390.0,390.0,0
17478,160000,2,3,2,26,-1,-1,-1,-1,-1,...,390.0,390.0,390.0,390.0,390.0,390.0,390.0,390.0,390.0,0
9374,180000,1,2,1,26,-1,-1,-1,-1,-1,...,396.0,396.0,396.0,396.0,396.0,396.0,396.0,396.0,396.0,0
23389,180000,1,2,1,26,-1,-1,-1,-1,-1,...,396.0,396.0,396.0,396.0,396.0,396.0,396.0,396.0,396.0,0
5630,180000,2,1,2,28,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
15573,180000,2,1,2,28,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12925,200000,2,1,1,34,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
22563,200000,2,1,1,34,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
20500,200000,2,1,1,36,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
22994,200000,2,1,1,36,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2121,210000,2,1,2,39,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4840,210000,2,1,2,39,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
9567,300000,1,1,2,27,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
21411,300000,1,1,2,27,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
5083,360000,1,1,2,29,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12509,360000,1,1,2,29,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4924,360000,1,1,2,32,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
23918,360000,1,1,2,32,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
889,360000,1,2,1,41,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
6675,360000,1,2,1,41,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
13782,360000,2,1,1,41,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
20462,360000,2,1,1,41,-2,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
14632,360000,2,1,2,29,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
17697,360000,2,1,2,29,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
680,500000,1,1,1,43,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
5891,500000,1,1,1,43,1,-2,-2,-2,-2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [144]:
df.drop_duplicates(inplace=True)

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23976 entries, 0 to 23999
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  23976 non-null  int64
 1   SEX        23976 non-null  int64
 2   EDUCATION  23976 non-null  int64
 3   MARRIAGE   23976 non-null  int64
 4   AGE        23976 non-null  int64
 5   PAY_1      23976 non-null  int64
 6   PAY_2      23976 non-null  int64
 7   PAY_3      23976 non-null  int64
 8   PAY_4      23976 non-null  int64
 9   PAY_5      23976 non-null  int64
 10  PAY_6      23976 non-null  int64
 11  BILL_AMT1  23976 non-null  float64
 12  BILL_AMT2  23976 non-null  float64
 13  BILL_AMT3  23976 non-null  float64
 14  BILL_AMT4  23976 non-null  float64
 15  BILL_AMT5  23976 non-null  float64
 16  BILL_AMT6  23976 non-null  float64
 17  PAY_AMT1   23976 non-null  float64
 18  PAY_AMT2   23976 non-null  float64
 19  PAY_AMT3   23976 non-null  float64
 20  PAY_AMT4   23976 non-null  float64
 21  PAY_AMT5   23976 non-null  float64
 22  PAY_AMT6   23976 non-null  float64
 23  default    23976 non-null  int64
dtypes: float64(12), int64(12)
memory usage: 4.6 MB

# Feature Enginnering

In [146]:
#Late_Repayment

pay_cols = [f"PAY_{i}" for i in range(1, 7)]
df["late_payment_count"] = (df[pay_cols] >= 1).sum(axis=1)

df["late_payment_count"].value_counts()

late_payment_count
0    15951
1     3550
2     1518
6     1075
3      906
4      744
5      232
Name: count, dtype: int64

In [147]:
df["severe_late_count"] = (df[pay_cols] >= 3).sum(axis=1)

df["severe_late_count"].value_counts()

severe_late_count
0    23040
1      516
2      175
4      120
3       79
5       24
6       22
Name: count, dtype: int64

In [148]:
df["max_delay"] = df[pay_cols].max(axis=1)

In [149]:
df["avg_pay_status"] = df[pay_cols].mean(axis=1)

In [150]:
#PAY-BILL Ratio

for i in range(1, 7):
    df[f"PAY_RATIO_{i}"] = (
        df[f"PAY_AMT{i}"] /
        (df[f"BILL_AMT{i}"].abs()+1)
    )
ratio_cols = [f"PAY_RATIO_{i}" for i in range(1, 7)]

df.groupby("default")[ratio_cols].median()

,PAY_RATIO_1,PAY_RATIO_2,PAY_RATIO_3,PAY_RATIO_4,PAY_RATIO_5,PAY_RATIO_6
default,,,,,,
0,0.062413,0.060103,0.048182,0.041304,0.044116,0.043749
1,0.047696,0.046520,0.038028,0.036976,0.038135,0.037720

In [151]:
df["avg_payment_ratio"] = df[ratio_cols].mean(axis=1)

In [152]:
#BILL_AMT Averaging and Max

bill_cols = [f"BILL_AMT{i}" for i in range(1, 7)]

df["avg_bill"] = df[bill_cols].mean(axis=1)
df["max_bill"] = df[bill_cols].max(axis=1)

In [153]:
#PAY_AMT Averaging and Max

pay_amt_cols = [f"PAY_AMT{i}" for i in range(1, 7)]

df["avg_payment"] = df[pay_amt_cols].mean(axis=1)
df["max_payment"] = df[pay_amt_cols].max(axis=1)

In [154]:
#Credit Utilization
df["avg_utilization"] = (
    df["avg_bill"].abs() /
    (df["LIMIT_BAL"] + 1)
)

In [155]:
engineered = [
    "late_payment_count",
    "avg_bill",
    "max_bill",
    "avg_payment",
    "max_payment",
    "avg_payment_ratio"
]

df.groupby("default")[engineered].mean().T

default                        0             1
late_payment_count      0.501419      1.985663
avg_bill            45247.661062  43713.729548
max_bill            62097.784203  54844.439540
avg_payment          5833.897189   3341.675722
max_payment         17498.207015  10084.271270
avg_payment_ratio     201.971874    115.802930

# Pre-Processing

In [156]:
drop = ['BILL_AMT1', 'BILL_AMT2','BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6',
        'PAY_AMT1','PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']
df.drop(columns=drop,inplace=True)

In [157]:
X = df.drop(columns=['default'])
y = df['default']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((19180, 27), (4796, 27), (19180,), (4796,))

In [158]:
categorical_features = ['SEX', 'EDUCATION', 'MARRIAGE']

numeric_features= [
    'LIMIT_BAL', 'AGE', 'PAY_1', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6',
    'late_payment_count','severe_late_count', 'max_delay', 'avg_pay_status', 'PAY_RATIO_1', 'PAY_RATIO_2', 'PAY_RATIO_3',
    'PAY_RATIO_4', 'PAY_RATIO_5', 'PAY_RATIO_6','avg_payment_ratio', 'avg_bill', 'max_bill',
    'avg_payment', 'max_payment', 'avg_utilization'
]

In [159]:
numeric_transformer = Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="median")),
        ("scaler",StandardScaler())
    ]
)

In [160]:
categorical_transformer = Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="most_frequent")),
        ("onehot",OneHotEncoder(handle_unknown="ignore",sparse_output=False))
    ]
)

In [161]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num",numeric_transformer,numeric_features),
        ("cat",categorical_transformer,categorical_features)
    ]
)

In [162]:
import joblib

preprocessor.fit(X_train)
joblib.dump(preprocessor,"../models/preprocessor.pkl")

['../models/preprocessor.pkl']

In [163]:
X_train.to_csv("../data/processed/X_train.csv",index=False)
X_test.to_csv("../data/processed/X_test.csv",index=False)
y_train.to_csv("../data/processed/y_train.csv",index=False)
y_test.to_csv("../data/processed/y_test.csv",index=False)